import { NextRequest, NextResponse } from 'next/server'

const jobs = new Map<string, any>()

export async function GET(request: NextRequest) {
    const { searchParams } = new URL(request.url)
    const jobId = searchParams.get('job_id')
    
    if (!jobId) {
        return NextResponse.json({ error: 'Missing job_id parameter' }, { status: 400 })
    }
    
    const job = jobs.get(jobId)
    
    if (!job) {
        return NextResponse.json({ error: 'Job not found' }, { status: 404 })
    }
    
    const notebookContent = job.notebook_content
    
    return new NextResponse(notebookContent, {
        headers: {
            'Content-Type': 'application/json',
            'Content-Disposition': `attachment; filename="system2ml-training-${jobId}.ipynb"`,
        },
    })
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json()
        const { dataset_profile, training_target, constraints } = body
        
        const jobId = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)
        
        const modelId = training_target?.base_model || 'microsoft/phi-2'
        const method = training_target?.method || 'lora'
        const maxBudget = training_target?.max_budget_usd || 10
        const datasetName = dataset_profile?.name || 'training_data'
        const datasetRows = dataset_profile?.rows || 'N/A'
        
        const notebook = {
            "cells": [
                {
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [
                        "# Fine-Tuning " + modelId.split('/').pop() + " with " + method.toUpperCase() + "\n\n",
                        "**System2ML Pipeline Training**  \n",
                        "Dataset: " + datasetName + " (" + datasetRows + " rows)  \n",
                        "---\n",
                        "This notebook was automatically generated by System2ML. ",
                        "Upload your dataset CSV file when prompted.\n"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 📦 Install Dependencies\n",
                        "!pip install -q transformers datasets peft accelerate bitsandbytes torch\n",
                        "!pip install -q scikit-learn pandas numpy\n",
                        "print(\"✅ Dependencies installed!\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # ⚙️ Configuration\n",
                        "import os\n",
                        "import json\n",
                        "import pandas as pd\n",
                        "import torch\n",
                        "from datetime import datetime\n",
                        "\n",
                        "# Configuration - Edit these values as needed\n",
                        "MODEL_NAME = \"" + modelId + "\"  # @param {type:\"string\"}\n",
                        "TRAINING_METHOD = \"" + method + "\"  # @param [\"lora\", \"qlora\", \"full_ft\"]\n",
                        "MAX_BUDGET_USD = " + maxBudget + "  # @param {type:\"number\"}\n",
                        "\n",
                        "print(f\"🤖 Model: {MODEL_NAME}\")\n",
                        "print(f\"🔧 Method: {TRAINING_METHOD}\")\n",
                        "print(f\"💰 Max Budget: ${MAX_BUDGET_USD}\")\n",
                        "print(f\"🖥️  Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 📂 Upload Dataset\n",
                        "from google.colab import files\n",
                        "\n",
                        "print(\"📁 Please upload your CSV dataset file:\")\n",
                        "uploaded = files.upload()\n",
                        "\n",
                        "if uploaded:\n",
                        "    filename = list(uploaded.keys())[0]\n",
                        "    df = pd.read_csv(filename)\n",
                        "    print(f\"✅ Dataset loaded: {len(df)} rows, {len(df.columns)} columns\")\n",
                        "    print(f\"📋 Columns: {list(df.columns)}\")\n",
                        "else:\n",
                        "    raise ValueError(\"No file uploaded!\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 🔄 Prepare Data\n",
                        "from sklearn.model_selection import train_test_split\n",
                        "\n",
                        "# Auto-detect label column\n",
                        "label_candidates = ['label', 'target', 'y', 'class', 'output', 'dependent']\n",
                        "label_col = next((c for c in df.columns if c.lower() in label_candidates), None)\n",
                        "if not label_col:\n",
                        "    label_col = df.columns[-1]\n",
                        "    print(f\"⚠️  No explicit label column found. Using last column: '{label_col}'\")\n",
                        "\n",
                        "feature_cols = [c for c in df.columns if c != label_col]\n",
                        "\n",
                        "X = df[feature_cols].values\n",
                        "y = df[label_col].values\n",
                        "\n",
                        "X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)\n",
                        "print(f\"✅ Data split - Train: {len(X_train)}, Validation: {len(X_val)}\")\n",
                        "print(f\"📊 Features: {len(feature_cols)}, Label: {label_col}\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 🤖 Load Model\n",
                        "from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer\n",
                        "from peft import LoraConfig, get_peft_model, TaskType\n",
                        "\n",
                        "print(\"Loading tokenizer...\")\n",
                        "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)\n",
                        "if tokenizer.pad_token is None:\n",
                        "    tokenizer.pad_token = tokenizer.eos_token\n",
                        "\n",
                        "print(\"Loading model...\")\n",
                        "model = AutoModelForCausalLM.from_pretrained(\n",
                        "    MODEL_NAME, \n",
                        "    device_map='auto', \n",
                        "    trust_remote_code=True\n",
                        ")\n",
                        "\n",
                        "# Configure LoRA based on method\n",
                        "if TRAINING_METHOD in ['lora', 'qlora']:\n",
                        "    lora_config = LoraConfig(\n",
                        "        r=8,\n",
                        "        lora_alpha=16,\n",
                        "        target_modules=['q_proj', 'v_proj'],\n",
                        "        lora_dropout=0.05,\n",
                        "        bias='none',\n",
                        "        task_type=TaskType.CAUSAL_LM\n",
                        "    )\n",
                        "    model = get_peft_model(model, lora_config)\n",
                        "    print(\"✅ LoRA configuration applied\")\n",
                        "\n",
                        "model.print_trainable_parameters()"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 📝 Tokenize Datasets\n",
                        "from datasets import Dataset\n",
                        "\n",
                        "# Convert to string format for language modeling\n",
                        "train_texts = [str(x) for x in X_train]\n",
                        "val_texts = [str(x) for x in X_val]\n",
                        "\n",
                        "train_dataset = Dataset.from_dict({'text': train_texts})\n",
                        "val_dataset = Dataset.from_dict({'text': val_texts})\n",
                        "\n",
                        "def tokenize_function(examples):\n",
                        "    return tokenizer(examples['text'], padding='max_length', truncation=True, max_length=512)\n",
                        "\n",
                        "train_dataset = train_dataset.map(tokenize_function, batched=True)\n",
                        "val_dataset = val_dataset.map(tokenize_function, batched=True)\n",
                        "\n",
                        "print(f\"✅ Tokenized {len(train_dataset)} training samples\")\n",
                        "print(f\"✅ Tokenized {len(val_dataset)} validation samples\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # ⚡ Training Configuration\n",
                        "training_args = TrainingArguments(\n",
                        "    output_dir='./results',\n",
                        "    num_train_epochs=3,  # @param {type:\"number\"}\n",
                        "    per_device_train_batch_size=4,  # @param {type:\"number\"}\n",
                        "    per_device_eval_batch_size=4,  # @param {type:\"number\"}\n",
                        "    warmup_steps=100,\n",
                        "    logging_dir='./logs',\n",
                        "    logging_steps=10,\n",
                        "    eval_strategy='epoch',\n",
                        "    save_strategy='epoch',\n",
                        "    load_best_model_at_end=True,\n",
                        "    metric_for_best_model='eval_loss',\n",
                        "    report_to='none',\n",
                        "    fp16=True,\n",
                        ")\n",
                        "\n",
                        "trainer = Trainer(\n",
                        "    model=model,\n",
                        "    args=training_args,\n",
                        "    train_dataset=train_dataset,\n",
                        "    eval_dataset=val_dataset,\n",
                        ")\n",
                        "\n",
                        "print(\"✅ Training configuration ready!\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 🚀 Start Training\n",
                        "import time\n",
                        "\n",
                        "start_time = time.time()\n",
                        "print(\"🚀 Starting training... This may take a while...\")\n",
                        "\n",
                        "trainer.train()\n",
                        "\n",
                        "elapsed_time = time.time() - start_time\n",
                        "print(f\"\\n✅ Training complete! Time: {elapsed_time/60:.2f} minutes\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": null,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# @title # 💾 Save & Download Model\n",
                        "output_dir = '/content/fine_tuned_model'\n",
                        "model.save_pretrained(output_dir)\n",
                        "tokenizer.save_pretrained(output_dir)\n",
                        "print(f\"✅ Model saved to {output_dir}\")\n",
                        "\n",
                        "# Download as zip\n",
                        "!zip -r model.zip {output_dir}\n",
                        "print(\"📦 Zipping model...\")\n",
                        "files.download('model.zip')\n",
                        "print(\"✅ Download started! Check your downloads folder.\")"
                    ]
                },
                {
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [
                        "---\n",
                        "## 🎉 Training Complete!\n",
                        "Your fine-tuned model is now ready. You can:\n",
                        "1. Download the model.zip file\n",
                        "2. Extract it locally\n",
                        "3. Use the model for inference\n",
                        "\n",
                        "**Next Steps:**\n",
                        "- Return to System2ML to deploy your model\n",
                        "- Or continue experimenting in Colab\n"
                    ]
                }
            ],
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "name": "python",
                    "version": "3.10.12"
                },
                "colab": {
                    "provenance": [],
                    "include_colab_link": true,
                    "name": "System2ML Training - " + modelId.split('/').pop()
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }
        
        const notebookJson = JSON.stringify(notebook, null, 2)
        
        const job = {
            job_id: jobId,
            status: 'created',
            config: {
                model_name: training_target?.base_model || 'microsoft/phi-2',
                method: training_target?.method || 'lora',
                max_budget: training_target?.max_budget_usd || 10,
                dataset_name: datasetName,
            },
            notebook_content: notebookJson,
            created_at: new Date().toISOString()
        }
        
        jobs.set(jobId, job)
        
        const response = {
            job_id: jobId,
            status: 'created',
            config: job.config,
            notebook_json: notebookJson,
            download_url: `/api/training/colab/download?job_id=${jobId}`,
            colab_url: `https://colab.research.google.com/#new`,
            notebook_filename: `system2ml-${modelId.split('/').pop()}-training-${jobId}.ipynb`,
            instructions: [
                '📥 Download the notebook using the button below',
                '📂 Go to https://colab.research.google.com',
                '📤 Click "Upload notebook" and select the downloaded file',
                '▶️ Run the cells in order to train your model',
                '💾 Download your fine-tuned model when complete'
            ],
            quick_start: {
                step1: 'Click "Download Notebook" below',
                step2: 'Go to Google Colab',
                step3: 'Upload the notebook file',
                step4: 'Run cells'
            }
        }
        
        return NextResponse.json(response)
        
    } catch (error: any) {
        console.error('Colab create error:', error)
        return NextResponse.json(
            { error: error.message || 'Failed to create Colab training' },
            { status: 500 }
        )
    }
}
